import { expect, test } from '@playwright/test'

test.describe('food v2 workflows', () => {
  test('creates and edits a structured recipe with a visible review workflow', async ({ page }) => {
    await page.goto('/#/food')
    await expect(page.getByRole('heading', { name: 'Your recipe shelf is ready' })).toBeVisible()
    await page.getByRole('button', { name: 'Add recipe' }).first().click()
    await page.getByLabel('Recipe name').fill('Lemon chickpea bowls')
    await page.getByLabel('Description').fill('A quick weeknight bowl.')
    await page.getByLabel('Source label', { exact: true }).fill('Family notebook')
    await page.getByLabel('Tags').fill('Quick, Vegetarian')
    await page.getByLabel('Ingredients', { exact: true }).fill('2 cup chickpeas\n1 cup rice\nsalt to taste')
    await page.getByLabel('Steps', { exact: true }).fill('Cook the rice.\nAssemble the bowls.')
    await page.getByRole('button', { name: 'Save recipe' }).click()
    await expect(page.getByRole('heading', { name: 'Lemon chickpea bowls' })).toBeVisible()
    await page.getByRole('button', { name: 'Edit' }).click()
    const editor = page.getByRole('dialog', { name: 'Edit Lemon chickpea bowls' })
    await expect(editor).toBeVisible()
    await editor.getByLabel('Notes', { exact: true }).fill('Finish with lemon zest.')
    await editor.getByRole('button', { name: 'Save changes' }).click()
    await page.getByRole('heading', { name: 'Lemon chickpea bowls' }).click()
    await expect(page.getByRole('heading', { name: 'Lemon chickpea bowls' })).toBeVisible()
    await expect(page.locator('.recipe-notes p')).toHaveText('Finish with lemon zest.')
  })

  test('pasted import becomes a Needs Review draft and can be corrected', async ({ page }) => {
    await page.goto('/#/food')
    await page.getByRole('button', { name: 'Import recipe' }).click()
    await page.getByText('Paste', { exact: true }).click()
    await page
      .getByLabel('JSON-LD, HTML, text, or caption')
      .fill('Toast and eggs\nIngredients\n2 each eggs\nsalt to taste\nInstructions\nToast bread.\nCook eggs.')
    await page.getByRole('button', { name: 'Parse pasted content' }).click()
    await expect(page.getByText('Needs Review', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Open review draft' }).click()
    const editor = page.getByRole('dialog', { name: 'Edit Toast and eggs' })
    await expect(editor.getByText('Needs review', { exact: true })).toBeVisible()
    await editor.getByRole('button', { name: 'Mark reviewed' }).click()
    await editor.getByRole('button', { name: 'Save changes' }).click()
    await expect(page.getByRole('heading', { name: 'Toast and eggs' })).toBeVisible()
  })

  test('planned nutrition is excluded until consumed servings are entered', async ({ page }) => {
    await page.goto('/#/food')
    await page.getByRole('button', { name: 'Add recipe' }).first().click()
    const recipeEditor = page.getByRole('dialog', { name: 'Create a recipe' })
    await recipeEditor.getByLabel('Recipe name').fill('Protein toast')
    await recipeEditor.getByLabel('Ingredients', { exact: true }).fill('2 each eggs')
    await recipeEditor.getByLabel('Steps', { exact: true }).fill('Cook and serve.')
    await recipeEditor.getByLabel('Calories (kcal)').fill('400')
    await recipeEditor.getByLabel('Protein (g)').fill('24')
    await recipeEditor.getByRole('button', { name: 'Save recipe' }).click()
    await page.getByText('Meal planner', { exact: true }).click()
    await page.locator('.meal-day.is-today').getByRole('button', { name: 'Add', exact: true }).first().click()
    const mealEditor = page.getByRole('dialog', { name: 'Plan breakfast' })
    await mealEditor.getByLabel('Saved recipe').selectOption({ label: 'Protein toast' })
    await mealEditor.getByLabel('Servings prepared').fill('3')
    await mealEditor.getByRole('button', { name: 'Plan meal' }).click()
    await page.getByText('Nutrition', { exact: true }).click()
    const consumedSummary = page.locator('.nutrition-summary__lead')
    await expect(consumedSummary.getByText('0 kcal')).toBeVisible()
    await page.getByText('Meal planner', { exact: true }).click()
    await page.getByLabel('Consumed servings for Protein toast').fill('1.5')
    await page.getByText('Nutrition', { exact: true }).click()
    await expect(consumedSummary.getByText('600 kcal')).toBeVisible()
    await page.getByText('Meal planner', { exact: true }).click()
    await expect(page.getByText('1.5 left')).toBeVisible()
    await expect(page.getByRole('heading', { name: 'Leftovers' })).toBeVisible()
  })
})
