// Generated by npm run contract:generate. Do not edit.
import Foundation

public struct AppData: Codable, Equatable {
    public var schemaVersion: Int
    public var initializedAt: String
    public var events: [CalendarEvent]
    public var assignments: [HomeworkAssignment]
    public var recipes: [Recipe]
    public var packagedFoods: [PackagedFood]
    public var meals: [MealEntry]
    public var leftovers: [Leftover]
    public var foodLog: [FoodLogEntry]
    public var pantry: [PantryItem]
    public var activeGroceryList: GroceryList?
    public var groceryHistory: [GroceryHistoryEntry]
    public var settings: UserSettings

    enum CodingKeys: String, CodingKey {
        case schemaVersion
        case initializedAt
        case events
        case assignments
        case recipes
        case packagedFoods
        case meals
        case leftovers
        case foodLog
        case pantry
        case activeGroceryList
        case groceryHistory
        case settings
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(schemaVersion, forKey: .schemaVersion)
        try container.encode(initializedAt, forKey: .initializedAt)
        try container.encode(events, forKey: .events)
        try container.encode(assignments, forKey: .assignments)
        try container.encode(recipes, forKey: .recipes)
        try container.encode(packagedFoods, forKey: .packagedFoods)
        try container.encode(meals, forKey: .meals)
        try container.encode(leftovers, forKey: .leftovers)
        try container.encode(foodLog, forKey: .foodLog)
        try container.encode(pantry, forKey: .pantry)
        try container.encode(activeGroceryList, forKey: .activeGroceryList)
        try container.encode(groceryHistory, forKey: .groceryHistory)
        try container.encode(settings, forKey: .settings)
    }
}

public struct CalendarEvent: Codable, Equatable {
    public var title: String
    public var date: String
    public var startTime: String
    public var endTime: String
    public var endDate: String?
    public var allDay: Bool?
    public var kind: String
    public var course: String?
    public var description: String?
    public var location: String?
    public var categories: [String]?
    public var sourceUrl: String?
    public var uid: String?
    public var sourceFeedId: String?
    public var sourceType: String?
    public var importedAt: String?
    public var assignmentId: String?
    public var locked: Bool?
    public var userAdjusted: Bool?
    public var completed: Bool?
    public var sourceLabel: String?
    public var id: String
    public var createdAt: String
    public var updatedAt: String
    public var source: String

    enum CodingKeys: String, CodingKey {
        case title
        case date
        case startTime
        case endTime
        case endDate
        case allDay
        case kind
        case course
        case description
        case location
        case categories
        case sourceUrl
        case uid
        case sourceFeedId
        case sourceType
        case importedAt
        case assignmentId
        case locked
        case userAdjusted
        case completed
        case sourceLabel
        case id
        case createdAt
        case updatedAt
        case source
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(title, forKey: .title)
        try container.encode(date, forKey: .date)
        try container.encode(startTime, forKey: .startTime)
        try container.encode(endTime, forKey: .endTime)
        try container.encodeIfPresent(endDate, forKey: .endDate)
        try container.encodeIfPresent(allDay, forKey: .allDay)
        try container.encode(kind, forKey: .kind)
        try container.encodeIfPresent(course, forKey: .course)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(location, forKey: .location)
        try container.encodeIfPresent(categories, forKey: .categories)
        try container.encodeIfPresent(sourceUrl, forKey: .sourceUrl)
        try container.encodeIfPresent(uid, forKey: .uid)
        try container.encodeIfPresent(sourceFeedId, forKey: .sourceFeedId)
        try container.encodeIfPresent(sourceType, forKey: .sourceType)
        try container.encodeIfPresent(importedAt, forKey: .importedAt)
        try container.encodeIfPresent(assignmentId, forKey: .assignmentId)
        try container.encodeIfPresent(locked, forKey: .locked)
        try container.encodeIfPresent(userAdjusted, forKey: .userAdjusted)
        try container.encodeIfPresent(completed, forKey: .completed)
        try container.encodeIfPresent(sourceLabel, forKey: .sourceLabel)
        try container.encode(id, forKey: .id)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(source, forKey: .source)
    }
}

public struct HomeworkAssignment: Codable, Equatable {
    public var title: String
    public var course: String
    public var dueDate: String
    public var dueTime: String
    public var priority: String
    public var estimatedMinutes: Decimal
    public var progress: Decimal
    public var status: String
    public var notes: String
    public var subtasks: [HomeworkSubtask]
    public var sourceLabel: String?
    public var sourceUrl: String?
    public var sourceFeedId: String?
    public var sourceType: String?
    public var externalId: String?
    public var importedAt: String?
    public var id: String
    public var createdAt: String
    public var updatedAt: String
    public var source: String

    enum CodingKeys: String, CodingKey {
        case title
        case course
        case dueDate
        case dueTime
        case priority
        case estimatedMinutes
        case progress
        case status
        case notes
        case subtasks
        case sourceLabel
        case sourceUrl
        case sourceFeedId
        case sourceType
        case externalId
        case importedAt
        case id
        case createdAt
        case updatedAt
        case source
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(title, forKey: .title)
        try container.encode(course, forKey: .course)
        try container.encode(dueDate, forKey: .dueDate)
        try container.encode(dueTime, forKey: .dueTime)
        try container.encode(priority, forKey: .priority)
        try container.encode(estimatedMinutes, forKey: .estimatedMinutes)
        try container.encode(progress, forKey: .progress)
        try container.encode(status, forKey: .status)
        try container.encode(notes, forKey: .notes)
        try container.encode(subtasks, forKey: .subtasks)
        try container.encodeIfPresent(sourceLabel, forKey: .sourceLabel)
        try container.encodeIfPresent(sourceUrl, forKey: .sourceUrl)
        try container.encodeIfPresent(sourceFeedId, forKey: .sourceFeedId)
        try container.encodeIfPresent(sourceType, forKey: .sourceType)
        try container.encodeIfPresent(externalId, forKey: .externalId)
        try container.encodeIfPresent(importedAt, forKey: .importedAt)
        try container.encode(id, forKey: .id)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(source, forKey: .source)
    }
}

public struct HomeworkSubtask: Codable, Equatable {
    public var id: String
    public var title: String
    public var completed: Bool

    enum CodingKeys: String, CodingKey {
        case id
        case title
        case completed
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(title, forKey: .title)
        try container.encode(completed, forKey: .completed)
    }
}

public struct Recipe: Codable, Equatable {
    public var name: String
    public var description: String
    public var notes: String?
    public var image: String
    public var category: String
    public var tags: [String]
    public var favorite: Bool
    public var originalYield: Decimal
    public var currentYield: Decimal?
    public var prepMinutes: Decimal
    public var cookMinutes: Decimal
    public var ingredients: [RecipeIngredient]
    public var steps: [RecipeStep]
    public var nutritionPerServing: Nutrition
    public var nutritionProvenance: NutritionProvenance
    public var sourceLabel: String
    public var sourceUrl: String?
    public var needsReview: Bool?
    public var reviewedAt: String?
    public var reviewNotes: String?
    public var id: String
    public var createdAt: String
    public var updatedAt: String
    public var source: String

    enum CodingKeys: String, CodingKey {
        case name
        case description
        case notes
        case image
        case category
        case tags
        case favorite
        case originalYield
        case currentYield
        case prepMinutes
        case cookMinutes
        case ingredients
        case steps
        case nutritionPerServing
        case nutritionProvenance
        case sourceLabel
        case sourceUrl
        case needsReview
        case reviewedAt
        case reviewNotes
        case id
        case createdAt
        case updatedAt
        case source
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(description, forKey: .description)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encode(image, forKey: .image)
        try container.encode(category, forKey: .category)
        try container.encode(tags, forKey: .tags)
        try container.encode(favorite, forKey: .favorite)
        try container.encode(originalYield, forKey: .originalYield)
        try container.encodeIfPresent(currentYield, forKey: .currentYield)
        try container.encode(prepMinutes, forKey: .prepMinutes)
        try container.encode(cookMinutes, forKey: .cookMinutes)
        try container.encode(ingredients, forKey: .ingredients)
        try container.encode(steps, forKey: .steps)
        try container.encode(nutritionPerServing, forKey: .nutritionPerServing)
        try container.encode(nutritionProvenance, forKey: .nutritionProvenance)
        try container.encode(sourceLabel, forKey: .sourceLabel)
        try container.encodeIfPresent(sourceUrl, forKey: .sourceUrl)
        try container.encodeIfPresent(needsReview, forKey: .needsReview)
        try container.encodeIfPresent(reviewedAt, forKey: .reviewedAt)
        try container.encodeIfPresent(reviewNotes, forKey: .reviewNotes)
        try container.encode(id, forKey: .id)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(source, forKey: .source)
    }
}

public struct RecipeIngredient: Codable, Equatable {
    public var id: String
    public var name: String
    public var canonicalName: String
    public var quantity: Decimal?
    public var unit: String
    public var category: String
    public var note: String?
    public var scaledOverride: RecipeIngredientScaledOverride?

    enum CodingKeys: String, CodingKey {
        case id
        case name
        case canonicalName
        case quantity
        case unit
        case category
        case note
        case scaledOverride
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(canonicalName, forKey: .canonicalName)
        try container.encode(quantity, forKey: .quantity)
        try container.encode(unit, forKey: .unit)
        try container.encode(category, forKey: .category)
        try container.encodeIfPresent(note, forKey: .note)
        try container.encodeIfPresent(scaledOverride, forKey: .scaledOverride)
    }
}

public struct RecipeIngredientScaledOverride: Codable, Equatable {
    public var yield: Decimal
    public var quantity: Decimal?
    public var unit: String

    enum CodingKeys: String, CodingKey {
        case yield
        case quantity
        case unit
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(yield, forKey: .yield)
        try container.encode(quantity, forKey: .quantity)
        try container.encode(unit, forKey: .unit)
    }
}

public struct RecipeStep: Codable, Equatable {
    public var id: String
    public var text: String

    enum CodingKeys: String, CodingKey {
        case id
        case text
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(text, forKey: .text)
    }
}

public struct Nutrition: Codable, Equatable {
    public var calories: Decimal
    public var protein: Decimal
    public var carbs: Decimal
    public var fat: Decimal
    public var sugar: Decimal?
    public var saturatedFat: Decimal?
    public var fiber: Decimal
    public var sodium: Decimal

    enum CodingKeys: String, CodingKey {
        case calories
        case protein
        case carbs
        case fat
        case sugar
        case saturatedFat
        case fiber
        case sodium
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(calories, forKey: .calories)
        try container.encode(protein, forKey: .protein)
        try container.encode(carbs, forKey: .carbs)
        try container.encode(fat, forKey: .fat)
        try container.encodeIfPresent(sugar, forKey: .sugar)
        try container.encodeIfPresent(saturatedFat, forKey: .saturatedFat)
        try container.encode(fiber, forKey: .fiber)
        try container.encode(sodium, forKey: .sodium)
    }
}

public struct NutritionProvenance: Codable, Equatable {
    public var kind: String
    public var capturedAt: String
    public var estimated: Bool
    public var sourceLabel: String?
    public var sourceUrl: String?

    enum CodingKeys: String, CodingKey {
        case kind
        case capturedAt
        case estimated
        case sourceLabel
        case sourceUrl
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(kind, forKey: .kind)
        try container.encode(capturedAt, forKey: .capturedAt)
        try container.encode(estimated, forKey: .estimated)
        try container.encodeIfPresent(sourceLabel, forKey: .sourceLabel)
        try container.encodeIfPresent(sourceUrl, forKey: .sourceUrl)
    }
}

public struct PackagedFood: Codable, Equatable {
    public var name: String
    public var brand: String?
    public var barcode: String?
    public var servingSize: PackagedFoodServingSize
    public var servingsPerContainer: Decimal?
    public var nutritionPerServing: Nutrition
    public var nutritionProvenance: NutritionProvenance
    public var image: String?
    public var notes: String?
    public var needsReview: Bool?
    public var reviewedAt: String?
    public var id: String
    public var createdAt: String
    public var updatedAt: String
    public var source: String

    enum CodingKeys: String, CodingKey {
        case name
        case brand
        case barcode
        case servingSize
        case servingsPerContainer
        case nutritionPerServing
        case nutritionProvenance
        case image
        case notes
        case needsReview
        case reviewedAt
        case id
        case createdAt
        case updatedAt
        case source
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(brand, forKey: .brand)
        try container.encodeIfPresent(barcode, forKey: .barcode)
        try container.encode(servingSize, forKey: .servingSize)
        try container.encodeIfPresent(servingsPerContainer, forKey: .servingsPerContainer)
        try container.encode(nutritionPerServing, forKey: .nutritionPerServing)
        try container.encode(nutritionProvenance, forKey: .nutritionProvenance)
        try container.encodeIfPresent(image, forKey: .image)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encodeIfPresent(needsReview, forKey: .needsReview)
        try container.encodeIfPresent(reviewedAt, forKey: .reviewedAt)
        try container.encode(id, forKey: .id)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(source, forKey: .source)
    }
}

public struct PackagedFoodServingSize: Codable, Equatable {
    public var quantity: Decimal
    public var unit: String

    enum CodingKeys: String, CodingKey {
        case quantity
        case unit
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(quantity, forKey: .quantity)
        try container.encode(unit, forKey: .unit)
    }
}

public struct MealEntry: Codable, Equatable {
    public var date: String
    public var slot: String
    public var recipeId: String?
    public var packagedFoodId: String?
    public var leftoverId: String?
    public var autoPlannedFromMealId: String?
    public var customName: String?
    public var servings: Decimal
    public var preparedServings: Decimal
    public var consumedServings: Decimal
    public var sourceSnapshot: MealSourceSnapshot
    public var id: String
    public var createdAt: String
    public var updatedAt: String
    public var source: String

    enum CodingKeys: String, CodingKey {
        case date
        case slot
        case recipeId
        case packagedFoodId
        case leftoverId
        case autoPlannedFromMealId
        case customName
        case servings
        case preparedServings
        case consumedServings
        case sourceSnapshot
        case id
        case createdAt
        case updatedAt
        case source
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(date, forKey: .date)
        try container.encode(slot, forKey: .slot)
        try container.encodeIfPresent(recipeId, forKey: .recipeId)
        try container.encodeIfPresent(packagedFoodId, forKey: .packagedFoodId)
        try container.encodeIfPresent(leftoverId, forKey: .leftoverId)
        try container.encodeIfPresent(autoPlannedFromMealId, forKey: .autoPlannedFromMealId)
        try container.encodeIfPresent(customName, forKey: .customName)
        try container.encode(servings, forKey: .servings)
        try container.encode(preparedServings, forKey: .preparedServings)
        try container.encode(consumedServings, forKey: .consumedServings)
        try container.encode(sourceSnapshot, forKey: .sourceSnapshot)
        try container.encode(id, forKey: .id)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(source, forKey: .source)
    }
}

public struct MealSourceSnapshot: Codable, Equatable {
    public var sourceType: String
    public var sourceId: String?
    public var name: String
    public var image: String?
    public var nutritionPerServing: Nutrition
    public var nutritionProvenance: NutritionProvenance
    public var capturedAt: String

    enum CodingKeys: String, CodingKey {
        case sourceType
        case sourceId
        case name
        case image
        case nutritionPerServing
        case nutritionProvenance
        case capturedAt
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sourceType, forKey: .sourceType)
        try container.encodeIfPresent(sourceId, forKey: .sourceId)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(image, forKey: .image)
        try container.encode(nutritionPerServing, forKey: .nutritionPerServing)
        try container.encode(nutritionProvenance, forKey: .nutritionProvenance)
        try container.encode(capturedAt, forKey: .capturedAt)
    }
}

public struct Leftover: Codable, Equatable {
    public var sourceMealId: String
    public var sourceSnapshot: MealSourceSnapshot
    public var preparedOn: String
    public var servingsRemaining: Decimal
    public var storageLocation: String
    public var useByDate: String?
    public var notes: String?
    public var id: String
    public var createdAt: String
    public var updatedAt: String
    public var source: String

    enum CodingKeys: String, CodingKey {
        case sourceMealId
        case sourceSnapshot
        case preparedOn
        case servingsRemaining
        case storageLocation
        case useByDate
        case notes
        case id
        case createdAt
        case updatedAt
        case source
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sourceMealId, forKey: .sourceMealId)
        try container.encode(sourceSnapshot, forKey: .sourceSnapshot)
        try container.encode(preparedOn, forKey: .preparedOn)
        try container.encode(servingsRemaining, forKey: .servingsRemaining)
        try container.encode(storageLocation, forKey: .storageLocation)
        try container.encodeIfPresent(useByDate, forKey: .useByDate)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encode(id, forKey: .id)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(source, forKey: .source)
    }
}

public struct FoodLogEntry: Codable, Equatable {
    public var date: String
    public var name: String
    public var servings: Decimal
    public var nutritionSnapshot: Nutrition
    public var provenanceSnapshot: NutritionProvenance
    public var sourceSnapshot: MealSourceSnapshot
    public var origin: String
    public var id: String
    public var createdAt: String
    public var updatedAt: String
    public var source: String

    enum CodingKeys: String, CodingKey {
        case date
        case name
        case servings
        case nutritionSnapshot
        case provenanceSnapshot
        case sourceSnapshot
        case origin
        case id
        case createdAt
        case updatedAt
        case source
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(date, forKey: .date)
        try container.encode(name, forKey: .name)
        try container.encode(servings, forKey: .servings)
        try container.encode(nutritionSnapshot, forKey: .nutritionSnapshot)
        try container.encode(provenanceSnapshot, forKey: .provenanceSnapshot)
        try container.encode(sourceSnapshot, forKey: .sourceSnapshot)
        try container.encode(origin, forKey: .origin)
        try container.encode(id, forKey: .id)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(source, forKey: .source)
    }
}

public struct PantryItem: Codable, Equatable {
    public var name: String
    public var canonicalName: String
    public var quantity: Decimal
    public var unit: String
    public var category: String
    public var location: String
    public var expirationDate: String?
    public var notes: String?
    public var id: String
    public var createdAt: String
    public var updatedAt: String
    public var source: String

    enum CodingKeys: String, CodingKey {
        case name
        case canonicalName
        case quantity
        case unit
        case category
        case location
        case expirationDate
        case notes
        case id
        case createdAt
        case updatedAt
        case source
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(canonicalName, forKey: .canonicalName)
        try container.encode(quantity, forKey: .quantity)
        try container.encode(unit, forKey: .unit)
        try container.encode(category, forKey: .category)
        try container.encode(location, forKey: .location)
        try container.encodeIfPresent(expirationDate, forKey: .expirationDate)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encode(id, forKey: .id)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(source, forKey: .source)
    }
}

public struct GroceryList: Codable, Equatable {
    public var name: String
    public var items: [GroceryItem]
    public var status: String
    public var sourceStartDate: String?
    public var sourceEndDate: String?
    public var sourceMealIds: [String]?
    public var completedAt: String?
    public var id: String
    public var createdAt: String
    public var updatedAt: String
    public var source: String

    enum CodingKeys: String, CodingKey {
        case name
        case items
        case status
        case sourceStartDate
        case sourceEndDate
        case sourceMealIds
        case completedAt
        case id
        case createdAt
        case updatedAt
        case source
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(items, forKey: .items)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(sourceStartDate, forKey: .sourceStartDate)
        try container.encodeIfPresent(sourceEndDate, forKey: .sourceEndDate)
        try container.encodeIfPresent(sourceMealIds, forKey: .sourceMealIds)
        try container.encodeIfPresent(completedAt, forKey: .completedAt)
        try container.encode(id, forKey: .id)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(source, forKey: .source)
    }
}

public struct GroceryItem: Codable, Equatable {
    public var name: String
    public var canonicalName: String
    public var quantity: Decimal
    public var unit: String
    public var category: String
    public var checked: Bool
    public var note: String?
    public var sourceRecipeIds: [String]
    public var pantryQuantity: Decimal
    public var pantryDecision: String
    public var pantryCustomQuantity: Decimal?
    public var needsReview: Bool?
    public var reviewReason: String?
    public var id: String
    public var createdAt: String
    public var updatedAt: String
    public var source: String

    enum CodingKeys: String, CodingKey {
        case name
        case canonicalName
        case quantity
        case unit
        case category
        case checked
        case note
        case sourceRecipeIds
        case pantryQuantity
        case pantryDecision
        case pantryCustomQuantity
        case needsReview
        case reviewReason
        case id
        case createdAt
        case updatedAt
        case source
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(canonicalName, forKey: .canonicalName)
        try container.encode(quantity, forKey: .quantity)
        try container.encode(unit, forKey: .unit)
        try container.encode(category, forKey: .category)
        try container.encode(checked, forKey: .checked)
        try container.encodeIfPresent(note, forKey: .note)
        try container.encode(sourceRecipeIds, forKey: .sourceRecipeIds)
        try container.encode(pantryQuantity, forKey: .pantryQuantity)
        try container.encode(pantryDecision, forKey: .pantryDecision)
        try container.encodeIfPresent(pantryCustomQuantity, forKey: .pantryCustomQuantity)
        try container.encodeIfPresent(needsReview, forKey: .needsReview)
        try container.encodeIfPresent(reviewReason, forKey: .reviewReason)
        try container.encode(id, forKey: .id)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(source, forKey: .source)
    }
}

public struct GroceryHistoryEntry: Codable, Equatable {
    public var name: String
    public var completedAt: String
    public var items: [GroceryItem]
    public var sourceStartDate: String?
    public var sourceEndDate: String?
    public var sourceMealIds: [String]?
    public var id: String
    public var createdAt: String
    public var updatedAt: String
    public var source: String

    enum CodingKeys: String, CodingKey {
        case name
        case completedAt
        case items
        case sourceStartDate
        case sourceEndDate
        case sourceMealIds
        case id
        case createdAt
        case updatedAt
        case source
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(completedAt, forKey: .completedAt)
        try container.encode(items, forKey: .items)
        try container.encodeIfPresent(sourceStartDate, forKey: .sourceStartDate)
        try container.encodeIfPresent(sourceEndDate, forKey: .sourceEndDate)
        try container.encodeIfPresent(sourceMealIds, forKey: .sourceMealIds)
        try container.encode(id, forKey: .id)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(source, forKey: .source)
    }
}

public struct UserSettings: Codable, Equatable {
    public var name: String
    public var measurementSystem: String
    public var appearance: String
    public var calendarTimeZone: String?
    public var nutritionTargets: Nutrition
    public var study: StudySettings
    public var mealPlanning: MealPlanningPreferences
    public var groceryCategories: [GroceryCategorySetting]
    public var groceryStaples: [GroceryStaple]
    public var calendarFeeds: [CalendarFeed]

    enum CodingKeys: String, CodingKey {
        case name
        case measurementSystem
        case appearance
        case calendarTimeZone
        case nutritionTargets
        case study
        case mealPlanning
        case groceryCategories
        case groceryStaples
        case calendarFeeds
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(measurementSystem, forKey: .measurementSystem)
        try container.encode(appearance, forKey: .appearance)
        try container.encodeIfPresent(calendarTimeZone, forKey: .calendarTimeZone)
        try container.encode(nutritionTargets, forKey: .nutritionTargets)
        try container.encode(study, forKey: .study)
        try container.encode(mealPlanning, forKey: .mealPlanning)
        try container.encode(groceryCategories, forKey: .groceryCategories)
        try container.encode(groceryStaples, forKey: .groceryStaples)
        try container.encode(calendarFeeds, forKey: .calendarFeeds)
    }
}

public struct StudySettings: Codable, Equatable {
    public var earliestTime: String
    public var latestTime: String
    public var defaultBlockMinutes: Decimal
    public var breakMinutes: Decimal
    public var maxBlockMinutes: Decimal
    public var avoidTimes: [AvoidTimeRange]

    enum CodingKeys: String, CodingKey {
        case earliestTime
        case latestTime
        case defaultBlockMinutes
        case breakMinutes
        case maxBlockMinutes
        case avoidTimes
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(earliestTime, forKey: .earliestTime)
        try container.encode(latestTime, forKey: .latestTime)
        try container.encode(defaultBlockMinutes, forKey: .defaultBlockMinutes)
        try container.encode(breakMinutes, forKey: .breakMinutes)
        try container.encode(maxBlockMinutes, forKey: .maxBlockMinutes)
        try container.encode(avoidTimes, forKey: .avoidTimes)
    }
}

public struct AvoidTimeRange: Codable, Equatable {
    public var id: String
    public var label: String
    public var days: [Decimal]
    public var startTime: String
    public var endTime: String

    enum CodingKeys: String, CodingKey {
        case id
        case label
        case days
        case startTime
        case endTime
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(label, forKey: .label)
        try container.encode(days, forKey: .days)
        try container.encode(startTime, forKey: .startTime)
        try container.encode(endTime, forKey: .endTime)
    }
}

public struct MealPlanningPreferences: Codable, Equatable {
    public var mode: String
    public var preferredSlots: [String]
    public var targetPrepServings: Decimal
    public var favorAvailablePantry: Bool
    public var lateDayNutritionBias: Bool?

    enum CodingKeys: String, CodingKey {
        case mode
        case preferredSlots
        case targetPrepServings
        case favorAvailablePantry
        case lateDayNutritionBias
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(mode, forKey: .mode)
        try container.encode(preferredSlots, forKey: .preferredSlots)
        try container.encode(targetPrepServings, forKey: .targetPrepServings)
        try container.encode(favorAvailablePantry, forKey: .favorAvailablePantry)
        try container.encodeIfPresent(lateDayNutritionBias, forKey: .lateDayNutritionBias)
    }
}

public struct GroceryCategorySetting: Codable, Equatable {
    public var id: String
    public var name: String
    public var sortOrder: Decimal
    public var enabled: Bool

    enum CodingKeys: String, CodingKey {
        case id
        case name
        case sortOrder
        case enabled
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(sortOrder, forKey: .sortOrder)
        try container.encode(enabled, forKey: .enabled)
    }
}

public struct GroceryStaple: Codable, Equatable {
    public var id: String
    public var name: String
    public var canonicalName: String
    public var quantity: Decimal
    public var unit: String
    public var category: String
    public var enabled: Bool

    enum CodingKeys: String, CodingKey {
        case id
        case name
        case canonicalName
        case quantity
        case unit
        case category
        case enabled
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(canonicalName, forKey: .canonicalName)
        try container.encode(quantity, forKey: .quantity)
        try container.encode(unit, forKey: .unit)
        try container.encode(category, forKey: .category)
        try container.encode(enabled, forKey: .enabled)
    }
}

public struct CalendarFeed: Codable, Equatable {
    public var id: String
    public var name: String
    public var kind: String
    public var importMode: String?
    public var url: String?
    public var enabled: Bool
    public var status: String
    public var lastRefresh: String?
    public var lastImportCount: Decimal?
    public var lastAssignmentCount: Decimal?

    enum CodingKeys: String, CodingKey {
        case id
        case name
        case kind
        case importMode
        case url
        case enabled
        case status
        case lastRefresh
        case lastImportCount
        case lastAssignmentCount
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(kind, forKey: .kind)
        try container.encodeIfPresent(importMode, forKey: .importMode)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encode(enabled, forKey: .enabled)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(lastRefresh, forKey: .lastRefresh)
        try container.encodeIfPresent(lastImportCount, forKey: .lastImportCount)
        try container.encodeIfPresent(lastAssignmentCount, forKey: .lastAssignmentCount)
    }
}
